---
- hosts: ws
  become: yes
  become_user: root 
  ignore_errors: yes
  tasks:
    - name: Delete old Artifact
     file:
       path: /opt/qa/spg/*.jar
       state: absent

    - name: Get the PID
      shell: lsof -i :8082
      register: pid_output

    - name: Kill Running App
      shell: kill -9 pid_output.stdout
      when: pid_output.stdout != ''
    
    - name: Download New Artifact  
      get_url:
        url: http://ec2-52-55-109-255.compute-1.amazonaws.com:8081/artifactory/geolocation/geo/bio_22.jar
        dest: /opt/qa/spg
        url_username: admin
        url_password: admin1234

    - name: Run the App
      shell: nohup java -jar /opt/qa/spg/*.jar > /opt/qa/spg.log 2>&1 &


